INSERT INTO `system_notify_template` (`name`, `code`, `nickname`, `content`, `type`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('新的审批', 'flow-task', '管理员', '{userName}提交的【{processName}】需要您审批，请及时处理', 2, '[\"userName\",\"processName\"]', 0, '', '1', '2025-08-05 11:05:35', '1', '2025-08-05 15:06:10', b'0');
INSERT INTO `system_notify_template` (`name`, `code`, `nickname`, `content`, `type`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('通过', 'flow-complete', '管理员', '您提交的审批【{processName}】已经通过', 2, '[\"processName\"]', 0, '', '1', '2025-08-05 15:05:48', '1', '2025-08-05 15:08:12', b'0');
INSERT INTO `system_notify_template` (`name`, `code`, `nickname`, `content`, `type`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('驳回', 'flow-reject', '管理员', '您提交的审批【{processName}】已被驳回', 2, '[\"processName\"]', 0, '', '1', '2025-08-05 15:06:55', '1', '2025-08-05 15:08:04', b'0');
INSERT INTO `system_notify_template` (`name`, `code`, `nickname`, `content`, `type`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('转交', 'flow-transfer', '管理员', '{userName}转交了一项审批任务给您处理', 2, '[\"userName\"]', 0, '', '1', '2025-08-05 15:07:52', '1', '2025-08-05 15:07:52', b'0');
INSERT INTO `system_notify_template` (`name`, `code`, `nickname`, `content`, `type`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('超时', 'flow-timeout', '管理员', '您有一项【{processName}】审批任务已超时处理', 2, '[\"processName\"]', 0, '', '1', '2025-08-05 15:08:55', '1', '2025-08-05 15:08:55', b'0');
INSERT INTO `system_notify_template` (`name`, `code`, `nickname`, `content`, `type`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('抄送', 'flow-cc', '管理员', '您收到【{processName}】的审批抄送，请知晓', 2, '[\"processName\"]', 0, '', '1', '2025-08-05 15:09:22', '1', '2025-08-05 15:09:22', b'0');


INSERT INTO `system_mail_account` (`mail`, `username`, `password`, `host`, `port`, `ssl_enable`, `starttls_enable`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('amxk_notic@securitymind.com.cn', 'amxk_notic@securitymind.com.cn', 'ZGhHoX37TVZgvACs', 'smtp.exmail.qq.com', 465, b'1', b'0', '1', '2025-08-07 14:46:53', '1', '2025-08-07 15:03:29', b'0');
INSERT INTO `system_mail_template` (`name`, `code`, `account_id`, `nickname`, `title`, `content`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('新的审批', 'flow-task', 5, '安迈信科管理系统', '新的审批任务', '<p>{userName}提交的【{processName}】需要您审批，请及时处理</p>', '[\"userName\",\"processName\"]', 0, '', '1', '2025-08-07 15:07:13', '1', '2025-08-07 15:07:13', b'0');
INSERT INTO `system_mail_template` (`name`, `code`, `account_id`, `nickname`, `title`, `content`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('通过', 'flow-complete', 5, '安迈信科管理系统', '审批已通过', '<p>您提交的审批【{processName}】已经通过</p>', '[\"processName\"]', 0, '', '1', '2025-08-07 15:07:13', '1', '2025-08-07 15:07:13', b'0');
INSERT INTO `system_mail_template` (`name`, `code`, `account_id`, `nickname`, `title`, `content`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('驳回', 'flow-reject', 5, '安迈信科管理系统', '审批被驳回', '<p>您提交的审批【{processName}】已被驳回</p>', '[\"processName\"]', 0, '', '1', '2025-08-07 15:07:13', '1', '2025-08-07 15:07:13', b'0');
INSERT INTO `system_mail_template` (`name`, `code`, `account_id`, `nickname`, `title`, `content`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('转交', 'flow-transfer', 5, '安迈信科管理系统', '新的审批任务', '<p>{userName}转交了一项审批任务给您处理</p>', '[\"userName\"]', 0, '', '1', '2025-08-07 15:07:13', '1', '2025-08-07 15:07:13', b'0');
INSERT INTO `system_mail_template` (`name`, `code`, `account_id`, `nickname`, `title`, `content`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('超时', 'flow-timeout', 5, '安迈信科管理系统', '审批任务超时', '<p>您有一项【{processName}】审批任务已超时处理</p>', '[\"processName\"]', 0, '', '1', '2025-08-07 15:07:13', '1', '2025-08-07 15:07:13', b'0');
INSERT INTO `system_mail_template` (`name`, `code`, `account_id`, `nickname`, `title`, `content`, `params`, `status`, `remark`, `creator`, `create_time`, `updater`, `update_time`, `deleted`) VALUES ('抄送', 'flow-cc', 5, '安迈信科管理系统', '抄送任务', '<p>您收到【{processName}】的审批抄送，请知晓</p>', '[\"processName\"]', 0, '', '1', '2025-08-07 15:07:13', '1', '2025-08-07 15:07:13', b'0');