spring:
  application:
    name: workflow-center
  datasource:
    dynamic:
      datasource:
        master:
          lazy: true
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.1.63:3306/workflow-center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: root
          password: amxk@2022
#        slave:
#          lazy: true
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/am_demo_slave?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
#          username: root
#          password: 123456
      druid:
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
  flyway:
    enabled: true
    # 非空数据库初始化Flyway时需要打开此开关进行Baseline操作
    baseline-on-migrate: true
    # 是否可以无序执行。开发环境最好开启 outOfOrder, 生产环境关闭 outOfOrder
    out-of-order: true
    # 迁移前校验 SQL 文件是否存在问题
    validate-on-migrate: true
    locations: classpath:db/master
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??sql??
    local-cache-scope: statement # ??????
  #  type-enums-package: com.amxk.entity.enums # ????? * ?? ; ??
  global-config:
    banner: false # ???????Logo
    map-underscore-to-camel-case: true